from django.db import models

class Conversation(models.Model):
    user_message = models.TextField()  # Stores the message from the user
    bot_response = models.TextField()  # Stores the response generated by the bot
    timestamp = models.DateTimeField(auto_now_add=True)  # Stores the timestamp of the conversation

    def __str__(self):
        return f"Conversation at {self.timestamp}: {self.user_message[:50]}..."

    class Meta:
        ordering = ['-timestamp']  # Orders conversations by most recent first
